using Enigma.Memory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Enigma.D3.UI.Controls
{
	public class UXButton : UXLabel
	{
		public new const int SizeOf = 0xF48;
		public new const int VTable = 0x01750C40;

		public int xC88_Neg1 { get { return Read<int>(0xC88); } }
		public int xC8C_Neg1 { get { return Read<int>(0xC8C); } }
		public int xC90_Neg1 { get { return Read<int>(0xC90); } }
		public int xC94_Neg1 { get { return Read<int>(0xC94); } }
		public int xC98_Neg1 { get { return Read<int>(0xC98); } }
		public int xC9C_Neg1 { get { return Read<int>(0xC9C); } }
		public int xCA0_Neg1 { get { return Read<int>(0xCA0); } }
		public int xCA4_Neg1 { get { return Read<int>(0xCA4); } }
		public int xCA8_Neg1 { get { return Read<int>(0xCA8); } }
		public int xCAC_Neg1 { get { return Read<int>(0xCAC); } }
		public int xCB0_Neg1 { get { return Read<int>(0xCB0); } }
		public int xCB4_Neg1 { get { return Read<int>(0xCB4); } }
		public int _xCB8 { get { return Read<int>(0xCB8); } }
		public int xCBC_Neg1 { get { return Read<int>(0xCBC); } }
		public int xCC0_Neg1 { get { return Read<int>(0xCC0); } }
		public int xCC4_Neg1 { get { return Read<int>(0xCC4); } }
		public int xCC8_Neg1 { get { return Read<int>(0xCC8); } }
		public int _xCCC { get { return Read<int>(0xCCC); } }
		public int _xCD0 { get { return Read<int>(0xCD0); } }
		public int _xCD4 { get { return Read<int>(0xCD4); } }
		public int _xCD8 { get { return Read<int>(0xCD8); } }
		public int _xCDC { get { return Read<int>(0xCDC); } }
		public int _xCE0 { get { return Read<int>(0xCE0); } }
		public int _xCE4 { get { return Read<int>(0xCE4); } }
		public int _xCE8 { get { return Read<int>(0xCE8); } }
		public int _xCEC { get { return Read<int>(0xCEC); } }
		public int _xCF0 { get { return Read<int>(0xCF0); } }
		public int _xCF4 { get { return Read<int>(0xCF4); } }
		public int _xCF8 { get { return Read<int>(0xCF8); } }
		public int _xCFC { get { return Read<int>(0xCFC); } }
		public int _xD00 { get { return Read<int>(0xD00); } }
		public int _xD04 { get { return Read<int>(0xD04); } }
		public int _xD08 { get { return Read<int>(0xD08); } }
		public int _xD0C { get { return Read<int>(0xD0C); } }
		public int _xD10 { get { return Read<int>(0xD10); } }
		public int _xD14 { get { return Read<int>(0xD14); } }
		public int _xD18 { get { return Read<int>(0xD18); } }
		public int _xD1C { get { return Read<int>(0xD1C); } }
		public int _xD20 { get { return Read<int>(0xD20); } }
		public int _xD24 { get { return Read<int>(0xD24); } }
		public int _xD28 { get { return Read<int>(0xD28); } }
		public int _xD2C { get { return Read<int>(0xD2C); } }
		public int _xD30 { get { return Read<int>(0xD30); } }
		public int _xD34 { get { return Read<int>(0xD34); } }
		public int _xD38 { get { return Read<int>(0xD38); } }
		public int _xD3C { get { return Read<int>(0xD3C); } }
		public int _xD40 { get { return Read<int>(0xD40); } }
		public int _xD44 { get { return Read<int>(0xD44); } }
		public int _xD48 { get { return Read<int>(0xD48); } }
		public int _xD4C { get { return Read<int>(0xD4C); } }
		public int _xD50 { get { return Read<int>(0xD50); } }
		public int _xD54 { get { return Read<int>(0xD54); } }
		public int _xD58 { get { return Read<int>(0xD58); } }
		public int _xD5C { get { return Read<int>(0xD5C); } }
		public int _xD60 { get { return Read<int>(0xD60); } }
		public int _xD64 { get { return Read<int>(0xD64); } }
		public int _xD68 { get { return Read<int>(0xD68); } }
		public int _xD6C { get { return Read<int>(0xD6C); } }
		public int _xD70 { get { return Read<int>(0xD70); } }
		public int _xD74 { get { return Read<int>(0xD74); } }
		public int _xD78 { get { return Read<int>(0xD78); } }
		public int _xD7C { get { return Read<int>(0xD7C); } }
		public int _xD80 { get { return Read<int>(0xD80); } }
		public int _xD84 { get { return Read<int>(0xD84); } }
		public int _xD88 { get { return Read<int>(0xD88); } }
		public int _xD8C { get { return Read<int>(0xD8C); } }
		public int _xD90 { get { return Read<int>(0xD90); } }
		public int _xD94 { get { return Read<int>(0xD94); } }
		public int _xD98 { get { return Read<int>(0xD98); } }
		public int _xD9C { get { return Read<int>(0xD9C); } }
		public int _xDA0 { get { return Read<int>(0xDA0); } }
		public int _xDA4 { get { return Read<int>(0xDA4); } }
		public int _xDA8 { get { return Read<int>(0xDA8); } }
		public int _xDAC { get { return Read<int>(0xDAC); } }
		public int _xDB0 { get { return Read<int>(0xDB0); } }
		public int _xDB4 { get { return Read<int>(0xDB4); } }
		public int _xDB8 { get { return Read<int>(0xDB8); } }
		public int _xDBC { get { return Read<int>(0xDBC); } }
		public int _xDC0 { get { return Read<int>(0xDC0); } }
		public int _xDC4 { get { return Read<int>(0xDC4); } }
		public int _xDC8 { get { return Read<int>(0xDC8); } }
		public int _xDCC { get { return Read<int>(0xDCC); } }
		public int _xDD0 { get { return Read<int>(0xDD0); } }
		public int _xDD4 { get { return Read<int>(0xDD4); } }
		public int _xDD8 { get { return Read<int>(0xDD8); } }
		public int _xDDC { get { return Read<int>(0xDDC); } }
		public int _xDE0 { get { return Read<int>(0xDE0); } }
		public int _xDE4 { get { return Read<int>(0xDE4); } }
		public int _xDE8 { get { return Read<int>(0xDE8); } }
		public int _xDEC { get { return Read<int>(0xDEC); } }
		public int _xDF0 { get { return Read<int>(0xDF0); } }
		public int _xDF4 { get { return Read<int>(0xDF4); } }
		public int _xDF8 { get { return Read<int>(0xDF8); } }
		public int _xDFC { get { return Read<int>(0xDFC); } }
		public int _xE00 { get { return Read<int>(0xE00); } }
		public int _xE04 { get { return Read<int>(0xE04); } }
		public int _xE08 { get { return Read<int>(0xE08); } }
		public int _xE0C { get { return Read<int>(0xE0C); } }
		public int _xE10 { get { return Read<int>(0xE10); } }
		public int _xE14 { get { return Read<int>(0xE14); } }
		public int _xE18 { get { return Read<int>(0xE18); } }
		public int _xE1C { get { return Read<int>(0xE1C); } }
		public int _xE20 { get { return Read<int>(0xE20); } }
		public int _xE24 { get { return Read<int>(0xE24); } }
		public int _xE28 { get { return Read<int>(0xE28); } }
		public int _xE2C { get { return Read<int>(0xE2C); } }
		public int _xE30 { get { return Read<int>(0xE30); } }
		public int _xE34 { get { return Read<int>(0xE34); } }
		public int _xE38 { get { return Read<int>(0xE38); } }
		public int _xE3C { get { return Read<int>(0xE3C); } }
		public int _xE40 { get { return Read<int>(0xE40); } }
		public int _xE44 { get { return Read<int>(0xE44); } }
		public int _xE48 { get { return Read<int>(0xE48); } }
		public int _xE4C { get { return Read<int>(0xE4C); } }
		public int _xE50 { get { return Read<int>(0xE50); } }
		public int _xE54 { get { return Read<int>(0xE54); } }
		public int _xE58 { get { return Read<int>(0xE58); } }
		public int _xE5C { get { return Read<int>(0xE5C); } }
		public int _xE60 { get { return Read<int>(0xE60); } }
		public int _xE64 { get { return Read<int>(0xE64); } }
		public int _xE68 { get { return Read<int>(0xE68); } }
		public int _xE6C { get { return Read<int>(0xE6C); } }
		public int _xE70 { get { return Read<int>(0xE70); } }
		public int _xE74 { get { return Read<int>(0xE74); } }
		public int _xE78 { get { return Read<int>(0xE78); } }
		public int _xE7C { get { return Read<int>(0xE7C); } }
		public int _xE80 { get { return Read<int>(0xE80); } }
		public int _xE84 { get { return Read<int>(0xE84); } }
		public int _xE88 { get { return Read<int>(0xE88); } }
		public int _xE8C { get { return Read<int>(0xE8C); } }
		public int _xE90 { get { return Read<int>(0xE90); } }
		public int _xE94 { get { return Read<int>(0xE94); } }
		public int _xE98 { get { return Read<int>(0xE98); } }
		public int _xE9C { get { return Read<int>(0xE9C); } }
		public int _xEA0 { get { return Read<int>(0xEA0); } }
		public int _xEA4 { get { return Read<int>(0xEA4); } }
		public int _xEA8 { get { return Read<int>(0xEA8); } }
		public int _xEAC { get { return Read<int>(0xEAC); } }
		public int _xEB0 { get { return Read<int>(0xEB0); } }
		public int _xEB4 { get { return Read<int>(0xEB4); } }
		public int _xEB8 { get { return Read<int>(0xEB8); } }
		public int _xEBC { get { return Read<int>(0xEBC); } }
		public int _xEC0 { get { return Read<int>(0xEC0); } }
		public int _xEC4 { get { return Read<int>(0xEC4); } }
		public int _xEC8 { get { return Read<int>(0xEC8); } }
		public int _xECC { get { return Read<int>(0xECC); } }
		public int _xED0 { get { return Read<int>(0xED0); } }
		public int _xED4 { get { return Read<int>(0xED4); } }
		public int _xED8 { get { return Read<int>(0xED8); } }
		public int _xEDC { get { return Read<int>(0xEDC); } }
		public int _xEE0 { get { return Read<int>(0xEE0); } }
		public int _xEE4 { get { return Read<int>(0xEE4); } }
		public int _xEE8 { get { return Read<int>(0xEE8); } }
		public int _xEEC { get { return Read<int>(0xEEC); } }
		public int _xEF0 { get { return Read<int>(0xEF0); } }
		public int _xEF4 { get { return Read<int>(0xEF4); } }
		public int _xEF8 { get { return Read<int>(0xEF8); } }
		public int _xEFC { get { return Read<int>(0xEFC); } }
		public int _xF00 { get { return Read<int>(0xF00); } }
		public int _xF04 { get { return Read<int>(0xF04); } }
		public int _xF08 { get { return Read<int>(0xF08); } }
		public int _xF0C { get { return Read<int>(0xF0C); } }
		public int _xF10 { get { return Read<int>(0xF10); } }
		public int _xF14 { get { return Read<int>(0xF14); } }
		public int _xF18 { get { return Read<int>(0xF18); } }
		public int _xF1C { get { return Read<int>(0xF1C); } }
		public int _xF20 { get { return Read<int>(0xF20); } }
		public int _xF24 { get { return Read<int>(0xF24); } }
		public int _xF28 { get { return Read<int>(0xF28); } }
		public int _xF2C { get { return Read<int>(0xF2C); } }
		public int _xF30 { get { return Read<int>(0xF30); } }
		public int _xF34 { get { return Read<int>(0xF34); } }
		public int _xF38 { get { return Read<int>(0xF38); } }
		public int _xF3C { get { return Read<int>(0xF3C); } }
		public int _xF40 { get { return Read<int>(0xF40); } }
		public int _xF44 { get { return Read<int>(0xF44); } }
	}
}
