using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Enigma.D3.UI
{
	public class UIControl : MemoryObject
	{
		// 2.0.4.23119
		
		// SizeOf = ???
		// I have no idea about typical size. I think size varies with control type.

		public UIControl(ProcessMemory memory, int address)
			: base(memory, address) { }

		public int x000_PtrVTable { get { return Field<int>(0x000); } }
		public int _x004 { get { return Field<int>(0x004); } }
		public int _x008 { get { return Field<int>(0x008); } }
		public int _x00C { get { return Field<int>(0x00C); } }
		public int _x010 { get { return Field<int>(0x010); } }
		public int _x014 { get { return Field<int>(0x014); } }
		public int _x018 { get { return Field<int>(0x018); } }
		public int _x01C { get { return Field<int>(0x01C); } }
		public int _x020 { get { return Field<int>(0x020); } }
		public int x024_Visibility { get { return Field<int>(0x024); } }
		public int _x028 { get { return Field<int>(0x028); } }
		public int _x02C { get { return Field<int>(0x02C); } }
		public UIReference x030_Self { get { return Field<UIReference>(0x030); } }
		public UIReference x238_Parent { get { return Field<UIReference>(0x238); } }
		public int _x340 { get { return Field<int>(0x340); } }
		public int _x344 { get { return Field<int>(0x344); } }
		public int _x348 { get { return Field<int>(0x348); } }
		public int _x34C { get { return Field<int>(0x34C); } }
		public int _x350 { get { return Field<int>(0x350); } }
		public int _x354 { get { return Field<int>(0x354); } }
		public int _x358 { get { return Field<int>(0x358); } }
		public int _x35C { get { return Field<int>(0x35C); } }
		public int _x360 { get { return Field<int>(0x360); } }
		public int _x364 { get { return Field<int>(0x364); } }
		public int _x368 { get { return Field<int>(0x368); } }
		public int _x36C { get { return Field<int>(0x36C); } }
		public int _x370 { get { return Field<int>(0x370); } }
		public int _x374 { get { return Field<int>(0x374); } }
		public int _x378 { get { return Field<int>(0x378); } }
		public int _x37C { get { return Field<int>(0x37C); } }
		public int _x380 { get { return Field<int>(0x380); } }
		public int _x384 { get { return Field<int>(0x384); } }
		public int _x388 { get { return Field<int>(0x388); } }
		public int _x38C { get { return Field<int>(0x38C); } }
		public int _x390 { get { return Field<int>(0x390); } }
		public int _x394 { get { return Field<int>(0x394); } }
		public int _x398 { get { return Field<int>(0x398); } }
		public int _x39C { get { return Field<int>(0x39C); } }
		public int _x3A0 { get { return Field<int>(0x3A0); } }
		public int _x3A4 { get { return Field<int>(0x3A4); } }
		public int _x3A8 { get { return Field<int>(0x3A8); } }
		public int _x3AC { get { return Field<int>(0x3AC); } }
		public int _x3B0 { get { return Field<int>(0x3B0); } }
		public int _x3B4 { get { return Field<int>(0x3B4); } }
		public int _x3B8 { get { return Field<int>(0x3B8); } }
		public int _x3BC { get { return Field<int>(0x3BC); } }
		public int _x3C0 { get { return Field<int>(0x3C0); } }
		public int _x3C4 { get { return Field<int>(0x3C4); } }
		public int _x3C8 { get { return Field<int>(0x3C8); } }
		public int _x3CC { get { return Field<int>(0x3CC); } }
		public int _x3D0 { get { return Field<int>(0x3D0); } }
		public int _x3D4 { get { return Field<int>(0x3D4); } }
		public int _x3D8 { get { return Field<int>(0x3D8); } }
		public int _x3DC { get { return Field<int>(0x3DC); } }
		public int _x3E0 { get { return Field<int>(0x3E0); } }
		public int _x3E4 { get { return Field<int>(0x3E4); } }
		public int _x3E8 { get { return Field<int>(0x3E8); } }
		public int _x3EC { get { return Field<int>(0x3EC); } }
		public int _x3F0 { get { return Field<int>(0x3F0); } }
		public int _x3F4 { get { return Field<int>(0x3F4); } }
		public int _x3F8 { get { return Field<int>(0x3F8); } }
		public int _x3FC { get { return Field<int>(0x3FC); } }
		public int _x400 { get { return Field<int>(0x400); } }
		public int _x404 { get { return Field<int>(0x404); } }
		public int _x408 { get { return Field<int>(0x408); } }
		public int _x40C { get { return Field<int>(0x40C); } }
		public int _x410 { get { return Field<int>(0x410); } }
		public int _x414 { get { return Field<int>(0x414); } }
		public int _x418 { get { return Field<int>(0x418); } }
		public int _x41C { get { return Field<int>(0x41C); } }
		public int _x420 { get { return Field<int>(0x420); } }
		public int _x424 { get { return Field<int>(0x424); } }
		public int _x428 { get { return Field<int>(0x428); } }
		public int _x42C { get { return Field<int>(0x42C); } }
		public int _x430 { get { return Field<int>(0x430); } }
		public int _x434 { get { return Field<int>(0x434); } }
		public int _x438 { get { return Field<int>(0x438); } }
		public int _x43C { get { return Field<int>(0x43C); } }
		public int _x440 { get { return Field<int>(0x440); } }
		public int _x444 { get { return Field<int>(0x444); } }
		public int _x448 { get { return Field<int>(0x448); } }
		public int _x44C { get { return Field<int>(0x44C); } }
		public int _x450 { get { return Field<int>(0x450); } }
		public int _x454 { get { return Field<int>(0x454); } }
		public int _x458 { get { return Field<int>(0x458); } }
		public int _x45C { get { return Field<int>(0x45C); } }
		public int _x460 { get { return Field<int>(0x460); } }
		public int _x464 { get { return Field<int>(0x464); } }
		public int _x468 { get { return Field<int>(0x468); } }
		public int _x46C { get { return Field<int>(0x46C); } }
		public int _x470 { get { return Field<int>(0x470); } }
		public int _x474 { get { return Field<int>(0x474); } }
		public int _x478 { get { return Field<int>(0x478); } }
		public int _x47C { get { return Field<int>(0x47C); } }
		public int _x480 { get { return Field<int>(0x480); } }
		public int _x484 { get { return Field<int>(0x484); } }
		public int _x488 { get { return Field<int>(0x488); } }
		public int _x48C { get { return Field<int>(0x48C); } }
		public int _x490 { get { return Field<int>(0x490); } }
		public int _x494 { get { return Field<int>(0x494); } }
		public int _x498 { get { return Field<int>(0x498); } }
		public int _x49C { get { return Field<int>(0x49C); } }
		public int _x4A0 { get { return Field<int>(0x4A0); } }
		public int _x4A4 { get { return Field<int>(0x4A4); } }
		public int _x4A8 { get { return Field<int>(0x4A8); } }
		public int _x4AC { get { return Field<int>(0x4AC); } }
		public int _x4B0 { get { return Field<int>(0x4B0); } }
		public int _x4B4 { get { return Field<int>(0x4B4); } }
		public int _x4B8 { get { return Field<int>(0x4B8); } }
		public int _x4BC { get { return Field<int>(0x4BC); } }
		public int _x4C0 { get { return Field<int>(0x4C0); } }
		public int _x4C4 { get { return Field<int>(0x4C4); } }
		public int _x4C8 { get { return Field<int>(0x4C8); } }
		public int _x4CC { get { return Field<int>(0x4CC); } }
		public int _x4D0 { get { return Field<int>(0x4D0); } }
		public int _x4D4 { get { return Field<int>(0x4D4); } }
		public int _x4D8 { get { return Field<int>(0x4D8); } }
		public int _x4DC { get { return Field<int>(0x4DC); } }
		public int _x4E0 { get { return Field<int>(0x4E0); } }
		public int _x4E4 { get { return Field<int>(0x4E4); } }
		public UIRect x4E8_UIRect { get { return Field<UIRect>(0x4E8); } }
		public int _x4EC { get { return Field<int>(0x4EC); } }
		public int _x4F0 { get { return Field<int>(0x4F0); } }
		public int _x4F4 { get { return Field<int>(0x4F4); } }
		public int _x4F8 { get { return Field<int>(0x4F8); } }
		public int _x4FC { get { return Field<int>(0x4FC); } }
		public int _x500 { get { return Field<int>(0x500); } }
		public int _x504 { get { return Field<int>(0x504); } }
		public int _x508 { get { return Field<int>(0x508); } }
		public int _x50C { get { return Field<int>(0x50C); } }
		public int _x510 { get { return Field<int>(0x510); } }
		public int _x514 { get { return Field<int>(0x514); } }
		public int _x518 { get { return Field<int>(0x518); } }
		public int _x51C { get { return Field<int>(0x51C); } }
		public int _x520 { get { return Field<int>(0x520); } }
		public int _x524 { get { return Field<int>(0x524); } }
		public int _x528 { get { return Field<int>(0x528); } }
		public int _x52C { get { return Field<int>(0x52C); } }
		public int _x530 { get { return Field<int>(0x530); } }
		public int _x534 { get { return Field<int>(0x534); } }
		public int _x538 { get { return Field<int>(0x538); } }
		public int _x53C { get { return Field<int>(0x53C); } }
		public int _x540 { get { return Field<int>(0x540); } }
		public int _x544 { get { return Field<int>(0x544); } }
		public int _x548 { get { return Field<int>(0x548); } }
		public int _x54C { get { return Field<int>(0x54C); } }
		public int _x550 { get { return Field<int>(0x550); } }
		public int _x554 { get { return Field<int>(0x554); } }
		public int _x558 { get { return Field<int>(0x558); } }
		public int _x55C { get { return Field<int>(0x55C); } }
		public int _x560 { get { return Field<int>(0x560); } }
		public int _x564 { get { return Field<int>(0x564); } }
		public int _x568 { get { return Field<int>(0x568); } }
		public int _x56C { get { return Field<int>(0x56C); } }
		public int _x570 { get { return Field<int>(0x570); } }
		public int _x574 { get { return Field<int>(0x574); } }
		public int _x578 { get { return Field<int>(0x578); } }
		public int _x57C { get { return Field<int>(0x57C); } }
		public int _x580 { get { return Field<int>(0x580); } }
		public int _x584 { get { return Field<int>(0x584); } }
		public int _x588 { get { return Field<int>(0x588); } }
		public int _x58C { get { return Field<int>(0x58C); } }
		public int _x590 { get { return Field<int>(0x590); } }
		public int _x594 { get { return Field<int>(0x594); } }
		public int _x598 { get { return Field<int>(0x598); } }
		public int _x59C { get { return Field<int>(0x59C); } }
		public int _x5A0 { get { return Field<int>(0x5A0); } }
		public int _x5A4 { get { return Field<int>(0x5A4); } }
		public int _x5A8 { get { return Field<int>(0x5A8); } }
		public int _x5AC { get { return Field<int>(0x5AC); } }
		public int _x5B0 { get { return Field<int>(0x5B0); } }
		public int _x5B4 { get { return Field<int>(0x5B4); } }
		public int _x5B8 { get { return Field<int>(0x5B8); } }
		public int _x5BC { get { return Field<int>(0x5BC); } }
		public int _x5C0 { get { return Field<int>(0x5C0); } }
		public int _x5C4 { get { return Field<int>(0x5C4); } }
		public int _x5C8 { get { return Field<int>(0x5C8); } }
		public int _x5CC { get { return Field<int>(0x5CC); } }
		public int _x5D0 { get { return Field<int>(0x5D0); } }
		public int _x5D4 { get { return Field<int>(0x5D4); } }
		public int _x5D8 { get { return Field<int>(0x5D8); } }
		public int _x5DC { get { return Field<int>(0x5DC); } }
		public int _x5E0 { get { return Field<int>(0x5E0); } }
		public int _x5E4 { get { return Field<int>(0x5E4); } }
		public int _x5E8 { get { return Field<int>(0x5E8); } }
		public int _x5EC { get { return Field<int>(0x5EC); } }
		public int _x5F0 { get { return Field<int>(0x5F0); } }
		public int _x5F4 { get { return Field<int>(0x5F4); } }
		public int _x5F8 { get { return Field<int>(0x5F8); } }
		public int _x5FC { get { return Field<int>(0x5FC); } }
		public int _x600 { get { return Field<int>(0x600); } }
		public int _x604 { get { return Field<int>(0x604); } }
		public int _x608 { get { return Field<int>(0x608); } }
		public int _x60C { get { return Field<int>(0x60C); } }
		public int _x610 { get { return Field<int>(0x610); } }
		public int _x614 { get { return Field<int>(0x614); } }
		public int _x618 { get { return Field<int>(0x618); } }
		public int _x61C { get { return Field<int>(0x61C); } }
		public int _x620 { get { return Field<int>(0x620); } }
		public int _x624 { get { return Field<int>(0x624); } }
		public int _x628 { get { return Field<int>(0x628); } }
		public int _x62C { get { return Field<int>(0x62C); } }
		public int _x630 { get { return Field<int>(0x630); } }
		public int _x634 { get { return Field<int>(0x634); } }
		public int _x638 { get { return Field<int>(0x638); } }
		public int _x63C { get { return Field<int>(0x63C); } }
		public int _x640 { get { return Field<int>(0x640); } }
		public int _x644 { get { return Field<int>(0x644); } }
		public int _x648 { get { return Field<int>(0x648); } }
		public int _x64C { get { return Field<int>(0x64C); } }
		public int _x650 { get { return Field<int>(0x650); } }
		public int _x654 { get { return Field<int>(0x654); } }
		public int _x658 { get { return Field<int>(0x658); } }
		public int _x65C { get { return Field<int>(0x65C); } }
		public int _x660 { get { return Field<int>(0x660); } }
		public int _x664 { get { return Field<int>(0x664); } }
		public int _x668 { get { return Field<int>(0x668); } }
		public int _x66C { get { return Field<int>(0x66C); } }
		public int _x670 { get { return Field<int>(0x670); } }
		public int _x674 { get { return Field<int>(0x674); } }
		public int _x678 { get { return Field<int>(0x678); } }
		public int _x67C { get { return Field<int>(0x67C); } }
		public int _x680 { get { return Field<int>(0x680); } }
		public int _x684 { get { return Field<int>(0x684); } }
		public int _x688 { get { return Field<int>(0x688); } }
		public int _x68C { get { return Field<int>(0x68C); } }
		public int _x690 { get { return Field<int>(0x690); } }
		public int _x694 { get { return Field<int>(0x694); } }
		public int _x698 { get { return Field<int>(0x698); } }
		public int _x69C { get { return Field<int>(0x69C); } }
		public int _x6A0 { get { return Field<int>(0x6A0); } }
		public int _x6A4 { get { return Field<int>(0x6A4); } }
		public int _x6A8 { get { return Field<int>(0x6A8); } }
		public int _x6AC { get { return Field<int>(0x6AC); } }
		public int _x6B0 { get { return Field<int>(0x6B0); } }
		public int _x6B4 { get { return Field<int>(0x6B4); } }
		public int _x6B8 { get { return Field<int>(0x6B8); } }
		public int _x6BC { get { return Field<int>(0x6BC); } }
		public int _x6C0 { get { return Field<int>(0x6C0); } }
		public int _x6C4 { get { return Field<int>(0x6C4); } }
		public int _x6C8 { get { return Field<int>(0x6C8); } }
		public int _x6CC { get { return Field<int>(0x6CC); } }
		public int _x6D0 { get { return Field<int>(0x6D0); } }
		public int _x6D4 { get { return Field<int>(0x6D4); } }
		public int _x6D8 { get { return Field<int>(0x6D8); } }
		public int _x6DC { get { return Field<int>(0x6DC); } }
		public int _x6E0 { get { return Field<int>(0x6E0); } }
		public int _x6E4 { get { return Field<int>(0x6E4); } }
		public int _x6E8 { get { return Field<int>(0x6E8); } }
		public int _x6EC { get { return Field<int>(0x6EC); } }
		public int _x6F0 { get { return Field<int>(0x6F0); } }
		public int _x6F4 { get { return Field<int>(0x6F4); } }
		public int _x6F8 { get { return Field<int>(0x6F8); } }
		public int _x6FC { get { return Field<int>(0x6FC); } }
		public int _x700 { get { return Field<int>(0x700); } }
		public int _x704 { get { return Field<int>(0x704); } }
		public int _x708 { get { return Field<int>(0x708); } }
		public int _x70C { get { return Field<int>(0x70C); } }
		public int _x710 { get { return Field<int>(0x710); } }
		public int _x714 { get { return Field<int>(0x714); } }
		public int _x718 { get { return Field<int>(0x718); } }
	}
}