public class MonsterAffixesEntry : MemoryObject
{
	// 2.0.5.24017
	public const int SizeOf = 0x388; // 904

	public MonsterAffixesEntry(ProcessMemory memory, int address)
		: base(memory, address) { }

	public string x000 { get { return Field(0x000, 256); } }
	public int x100 { get { return Field<int>(0x100); } }
	public int x104 { get { return Field<int>(0x104); } }
	public int x108 { get { return Field<int>(0x108); } }
	public int x10C { get { return Field<int>(0x10C); } }
	public int x110 { get { return Field<int>(0x110); } }
	public int x114_Enum { get { return Field<int>(0x114); } } // 0: All, 1: Rares, 2: Shooters, 3: Champions
	public int x118_Enum { get { return Field<int>(0x118); } } // -1: None, 0: Physical, 1: Fire, 2: Lightning, 3: Cold, 4: Poison, 5: Arcane, 6: Holy
	public int x11C_Enum { get { return Field<int>(0x11C); } } // 0: Prefix, 1: Suffix, 2: Inherent, 5: Title, 6: Quality, 7: Immunity, 9: Random, 10: Enchantment, 11: Socket Enhancement
	public int x120 { get { return Field<int>(0x120); } }
	public int x124 { get { return Field<int>(0x124); } }
	public int x128 { get { return Field<int>(0x128); } }
	public int x12C { get { return Field<int>(0x12C); } }
	public DT_TRANSLATEABLE x130 { get { return Field<DT_TRANSLATEABLE>(0x130); } }
	public DT_ATTRIBUTEPARAM x134 { get { return Field<DT_ATTRIBUTEPARAM>(0x134); } }
	public DT_FORMULA x138 { get { return Field<DT_FORMULA>(0x138); } }
	public SerializeData x140 { get { return Field<SerializeData>(0x140); } }
	public DT_TRANSLATEABLE x148 { get { return Field<DT_TRANSLATEABLE>(0x148); } }
	public DT_ATTRIBUTEPARAM x14C { get { return Field<DT_ATTRIBUTEPARAM>(0x14C); } }
	public DT_FORMULA x150 { get { return Field<DT_FORMULA>(0x150); } }
	public SerializeData x158 { get { return Field<SerializeData>(0x158); } }
	public DT_TRANSLATEABLE x160 { get { return Field<DT_TRANSLATEABLE>(0x160); } }
	public DT_ATTRIBUTEPARAM x164 { get { return Field<DT_ATTRIBUTEPARAM>(0x164); } }
	public DT_FORMULA x168 { get { return Field<DT_FORMULA>(0x168); } }
	public SerializeData x170 { get { return Field<SerializeData>(0x170); } }
	public DT_TRANSLATEABLE x178 { get { return Field<DT_TRANSLATEABLE>(0x178); } }
	public DT_ATTRIBUTEPARAM x17C { get { return Field<DT_ATTRIBUTEPARAM>(0x17C); } }
	public DT_FORMULA x180 { get { return Field<DT_FORMULA>(0x180); } }
	public SerializeData x188 { get { return Field<SerializeData>(0x188); } }
	public DT_TRANSLATEABLE x190 { get { return Field<DT_TRANSLATEABLE>(0x190); } }
	public DT_ATTRIBUTEPARAM x194 { get { return Field<DT_ATTRIBUTEPARAM>(0x194); } }
	public DT_FORMULA x198 { get { return Field<DT_FORMULA>(0x198); } }
	public SerializeData x1A0 { get { return Field<SerializeData>(0x1A0); } }
	public DT_TRANSLATEABLE x1A8 { get { return Field<DT_TRANSLATEABLE>(0x1A8); } }
	public DT_ATTRIBUTEPARAM x1AC { get { return Field<DT_ATTRIBUTEPARAM>(0x1AC); } }
	public DT_FORMULA x1B0 { get { return Field<DT_FORMULA>(0x1B0); } }
	public SerializeData x1B8 { get { return Field<SerializeData>(0x1B8); } }
	public DT_TRANSLATEABLE x1C0 { get { return Field<DT_TRANSLATEABLE>(0x1C0); } }
	public DT_ATTRIBUTEPARAM x1C4 { get { return Field<DT_ATTRIBUTEPARAM>(0x1C4); } }
	public DT_FORMULA x1C8 { get { return Field<DT_FORMULA>(0x1C8); } }
	public SerializeData x1D0 { get { return Field<SerializeData>(0x1D0); } }
	public DT_TRANSLATEABLE x1D8 { get { return Field<DT_TRANSLATEABLE>(0x1D8); } }
	public DT_ATTRIBUTEPARAM x1DC { get { return Field<DT_ATTRIBUTEPARAM>(0x1DC); } }
	public DT_FORMULA x1E0 { get { return Field<DT_FORMULA>(0x1E0); } }
	public SerializeData x1E8 { get { return Field<SerializeData>(0x1E8); } }
	public DT_TRANSLATEABLE x1F0 { get { return Field<DT_TRANSLATEABLE>(0x1F0); } }
	public DT_ATTRIBUTEPARAM x1F4 { get { return Field<DT_ATTRIBUTEPARAM>(0x1F4); } }
	public DT_FORMULA x1F8 { get { return Field<DT_FORMULA>(0x1F8); } }
	public SerializeData x200 { get { return Field<SerializeData>(0x200); } }
	public DT_TRANSLATEABLE x208 { get { return Field<DT_TRANSLATEABLE>(0x208); } }
	public DT_ATTRIBUTEPARAM x20C { get { return Field<DT_ATTRIBUTEPARAM>(0x20C); } }
	public DT_FORMULA x210 { get { return Field<DT_FORMULA>(0x210); } }
	public SerializeData x218 { get { return Field<SerializeData>(0x218); } }
	public DT_TRANSLATEABLE x220 { get { return Field<DT_TRANSLATEABLE>(0x220); } }
	public DT_ATTRIBUTEPARAM x224 { get { return Field<DT_ATTRIBUTEPARAM>(0x224); } }
	public DT_FORMULA x228 { get { return Field<DT_FORMULA>(0x228); } }
	public SerializeData x230 { get { return Field<SerializeData>(0x230); } }
	public DT_TRANSLATEABLE x238 { get { return Field<DT_TRANSLATEABLE>(0x238); } }
	public DT_ATTRIBUTEPARAM x23C { get { return Field<DT_ATTRIBUTEPARAM>(0x23C); } }
	public DT_FORMULA x240 { get { return Field<DT_FORMULA>(0x240); } }
	public SerializeData x248 { get { return Field<SerializeData>(0x248); } }
	public DT_TRANSLATEABLE x250 { get { return Field<DT_TRANSLATEABLE>(0x250); } }
	public DT_ATTRIBUTEPARAM x254 { get { return Field<DT_ATTRIBUTEPARAM>(0x254); } }
	public DT_FORMULA x258 { get { return Field<DT_FORMULA>(0x258); } }
	public SerializeData x260 { get { return Field<SerializeData>(0x260); } }
	public DT_TRANSLATEABLE x268 { get { return Field<DT_TRANSLATEABLE>(0x268); } }
	public DT_ATTRIBUTEPARAM x26C { get { return Field<DT_ATTRIBUTEPARAM>(0x26C); } }
	public DT_FORMULA x270 { get { return Field<DT_FORMULA>(0x270); } }
	public SerializeData x278 { get { return Field<SerializeData>(0x278); } }
	public DT_TRANSLATEABLE x280 { get { return Field<DT_TRANSLATEABLE>(0x280); } }
	public DT_ATTRIBUTEPARAM x284 { get { return Field<DT_ATTRIBUTEPARAM>(0x284); } }
	public DT_FORMULA x288 { get { return Field<DT_FORMULA>(0x288); } }
	public SerializeData x290 { get { return Field<SerializeData>(0x290); } }
	public DT_TRANSLATEABLE x298 { get { return Field<DT_TRANSLATEABLE>(0x298); } }
	public DT_ATTRIBUTEPARAM x29C { get { return Field<DT_ATTRIBUTEPARAM>(0x29C); } }
	public DT_FORMULA x2A0 { get { return Field<DT_FORMULA>(0x2A0); } }
	public SerializeData x2A8 { get { return Field<SerializeData>(0x2A8); } }
	public DT_TRANSLATEABLE x2B0 { get { return Field<DT_TRANSLATEABLE>(0x2B0); } }
	public DT_ATTRIBUTEPARAM x2B4 { get { return Field<DT_ATTRIBUTEPARAM>(0x2B4); } }
	public DT_FORMULA x2B8 { get { return Field<DT_FORMULA>(0x2B8); } }
	public SerializeData x2C0 { get { return Field<SerializeData>(0x2C0); } }
	public DT_TRANSLATEABLE x2C8 { get { return Field<DT_TRANSLATEABLE>(0x2C8); } }
	public DT_ATTRIBUTEPARAM x2CC { get { return Field<DT_ATTRIBUTEPARAM>(0x2CC); } }
	public DT_FORMULA x2D0 { get { return Field<DT_FORMULA>(0x2D0); } }
	public SerializeData x2D8 { get { return Field<SerializeData>(0x2D8); } }
	public DT_TRANSLATEABLE x2E0 { get { return Field<DT_TRANSLATEABLE>(0x2E0); } }
	public DT_ATTRIBUTEPARAM x2E4 { get { return Field<DT_ATTRIBUTEPARAM>(0x2E4); } }
	public DT_FORMULA x2E8 { get { return Field<DT_FORMULA>(0x2E8); } }
	public SerializeData x2F0 { get { return Field<SerializeData>(0x2F0); } }
	public DT_TRANSLATEABLE x2F8 { get { return Field<DT_TRANSLATEABLE>(0x2F8); } }
	public DT_ATTRIBUTEPARAM x2FC { get { return Field<DT_ATTRIBUTEPARAM>(0x2FC); } }
	public DT_FORMULA x300 { get { return Field<DT_FORMULA>(0x300); } }
	public SerializeData x308 { get { return Field<SerializeData>(0x308); } }
	public int x314_PowerSnoId { get { return Field<int>(0x314); } }
	public int x318_PowerSnoId { get { return Field<int>(0x318); } }
	public int x31C_PowerSnoId { get { return Field<int>(0x31C); } }
	public int x320 { get { return Field<int>(0x320); } }
	public int x321 { get { return Field<int>(0x321); } }
	public int x322 { get { return Field<int>(0x322); } }
	public int x323 { get { return Field<int>(0x323); } }
	public int x324 { get { return Field<int>(0x324); } }
	public int x325 { get { return Field<int>(0x325); } }
	public int x326 { get { return Field<int>(0x326); } }
	public int x327 { get { return Field<int>(0x327); } }
	public int x328 { get { return Field<int>(0x328); } }
	public int x329 { get { return Field<int>(0x329); } }
	public int x32A { get { return Field<int>(0x32A); } }
	public int x32B { get { return Field<int>(0x32B); } }
	public int x32C { get { return Field<int>(0x32C); } }
	public int x32D { get { return Field<int>(0x32D); } }
	public int x32E { get { return Field<int>(0x32E); } }
	public int x32F { get { return Field<int>(0x32F); } }
	public int x330 { get { return Field<int>(0x330); } }
	public int x331 { get { return Field<int>(0x331); } }
	public int x332 { get { return Field<int>(0x332); } }
	public int x333 { get { return Field<int>(0x333); } }
	public int x334 { get { return Field<int>(0x334); } }
	public int x335 { get { return Field<int>(0x335); } }
	public int x336 { get { return Field<int>(0x336); } }
	public int x337 { get { return Field<int>(0x337); } }
	public int x338 { get { return Field<int>(0x338); } }
	public int x339 { get { return Field<int>(0x339); } }
	public int x33A { get { return Field<int>(0x33A); } }
	public int x33B { get { return Field<int>(0x33B); } }
	public int x33C { get { return Field<int>(0x33C); } }
	public int x33D { get { return Field<int>(0x33D); } }
	public int x33E { get { return Field<int>(0x33E); } }
	public int x33F { get { return Field<int>(0x33F); } }
	public int x340 { get { return Field<int>(0x340); } }
	public int x341 { get { return Field<int>(0x341); } }
	public int x342 { get { return Field<int>(0x342); } }
	public int x343 { get { return Field<int>(0x343); } }
	public int x344 { get { return Field<int>(0x344); } }
	public int x345 { get { return Field<int>(0x345); } }
	public int x346 { get { return Field<int>(0x346); } }
	public int x347 { get { return Field<int>(0x347); } }
	public int x348 { get { return Field<int>(0x348); } }
	public int x349 { get { return Field<int>(0x349); } }
	public int x34A { get { return Field<int>(0x34A); } }
	public int x34B { get { return Field<int>(0x34B); } }
	public int x34C { get { return Field<int>(0x34C); } }
	public int x34D { get { return Field<int>(0x34D); } }
	public int x34E { get { return Field<int>(0x34E); } }
	public int x34F { get { return Field<int>(0x34F); } }
	public int x350 { get { return Field<int>(0x350); } }
	public int x351 { get { return Field<int>(0x351); } }
	public int x352 { get { return Field<int>(0x352); } }
	public int x353 { get { return Field<int>(0x353); } }
	public int x354 { get { return Field<int>(0x354); } }
	public int x355 { get { return Field<int>(0x355); } }
	public int x356 { get { return Field<int>(0x356); } }
	public int x357 { get { return Field<int>(0x357); } }
	public int x358 { get { return Field<int>(0x358); } }
	public int x359 { get { return Field<int>(0x359); } }
	public int x35A { get { return Field<int>(0x35A); } }
	public int x35B { get { return Field<int>(0x35B); } }
	public int x35C { get { return Field<int>(0x35C); } }
	public int x35D { get { return Field<int>(0x35D); } }
	public int x35E { get { return Field<int>(0x35E); } }
	public int x35F { get { return Field<int>(0x35F); } }
	public int x360 { get { return Field<int>(0x360); } }
	public int x361 { get { return Field<int>(0x361); } }
	public int x362 { get { return Field<int>(0x362); } }
	public int x363 { get { return Field<int>(0x363); } }
	public int x364 { get { return Field<int>(0x364); } }
	public int x365 { get { return Field<int>(0x365); } }
	public int x366 { get { return Field<int>(0x366); } }
	public int x367 { get { return Field<int>(0x367); } }
	public int x368 { get { return Field<int>(0x368); } }
	public int x369 { get { return Field<int>(0x369); } }
	public int x36A { get { return Field<int>(0x36A); } }
	public int x36B { get { return Field<int>(0x36B); } }
	public int x36C { get { return Field<int>(0x36C); } }
	public int x36D { get { return Field<int>(0x36D); } }
	public int x36E { get { return Field<int>(0x36E); } }
	public int x36F { get { return Field<int>(0x36F); } }
	public int x370 { get { return Field<int>(0x370); } }
	public int x371 { get { return Field<int>(0x371); } }
	public int x372 { get { return Field<int>(0x372); } }
	public int x373 { get { return Field<int>(0x373); } }
	public int x374 { get { return Field<int>(0x374); } }
	public int x375 { get { return Field<int>(0x375); } }
	public int x376 { get { return Field<int>(0x376); } }
	public int x377 { get { return Field<int>(0x377); } }
	public int x378 { get { return Field<int>(0x378); } }
	public int x379 { get { return Field<int>(0x379); } }
	public int x37A { get { return Field<int>(0x37A); } }
	public int x37B { get { return Field<int>(0x37B); } }
	public int x37C { get { return Field<int>(0x37C); } }
	public int x37D { get { return Field<int>(0x37D); } }
	public int x37E { get { return Field<int>(0x37E); } }
	public int x37F { get { return Field<int>(0x37F); } }
	public int x380 { get { return Field<int>(0x380); } }
	public int x381 { get { return Field<int>(0x381); } }
	public int x382 { get { return Field<int>(0x382); } }
}
